#!/usr/bin/env bash

build() {
    add_module cifs
    add_binary mount.cifs
    add_dir '/samba'
}

help() {
    cat <<HELPEOF
Adds SAMBA/CIFS module to initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
