#!/usr/bin/env bash

build() {
    local applet

    add_binary /usr/lib/initcpio/busybox /bin/busybox

    for applet in $(/usr/lib/initcpio/busybox --list); do
        add_symlink "/usr/bin/$applet" busybox
    done

    # add kmod with applet symlinks
    add_binary kmod
    for applet in {dep,ins,rm,ls}mod mod{probe,info}; do
        add_symlink "/usr/bin/$applet" kmod
    done

    add_binary blkid
    map add_binary mount umount
    add_binary switch_root

    add_file "/usr/lib/initcpio/init_functions" "/init_functions"
    if [ -r "/usr/lib/initcpio/skuf_data/init" ]; then
        add_file "/usr/lib/initcpio/skuf_data/init" "/init"
    else
        error "%s is not readable. Creating empty initramfs..." "init"
        add_file "/usr/lib/initcpio/skuf_data/notinit" "/init"
    fi
}

help() {
    cat <<HELPEOF
This hook provides crucial runtime necessities for booting. DO NOT
remove this hook unless you know what you're doing.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
