#!/usr/bin/env bash

build() {
    if [[ ! -x "$BUILDROOT/usr/lib/systemd/systemd-udevd" ]]; then
        warning 'udev daemon not found in $BUILDROOT. Too early?'
    fi

    if [[ -x "/usr/lib/dhcpcd/dev/udev.so" ]]; then
        add_binary "/usr/lib/dhcpcd/dev/udev.so"
    else
        error 'dhcpcd udev module was requested, but not found'
    fi
}

help() {
    cat <<HELPEOF
Adds dhcpcd udev module to initramfs.
Should be added AFTER udev hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
