#!/usr/bin/env bash

build() {
    add_file "/usr/lib/initcpio/skuf_data/banner_usb" "/banner_usb"
}

help() {
    cat <<HELPEOF
Adds colorful rainbow banner to initramfs (usb).
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
