#!/usr/bin/env bash

build() {
    [ -d "$BUILDROOT"/etc ] || add_dir "/etc" 755
    >"$BUILDROOT/etc/resolv.conf"
    chmod 644 "$BUILDROOT/etc/resolv.conf"

    add_binary /usr/lib/libnss_files.so.2
    add_binary /usr/lib/libnss_dns.so.2
    echo "hosts: files dns" >> "$BUILDROOT/etc/nsswitch.conf"
    echo "127.0.0.1 localhost" > "$BUILDROOT/etc/hosts"
    echo "::1       localhost" >> "$BUILDROOT/etc/hosts"

    add_all_modules -f 'wireless' '/drivers/net/'
}

help() {
    cat <<HELPEOF
Adds all network modules and resolv.conf, nsswitch.conf, hosts files
to initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
