#!/usr/bin/env bash

build() {
    add_binary base64
    add_binary openssl
    [ -x "$BUILDROOT/usr/bin/install" ] || add_binary install || return 1
    add_binary tty
    add_binary stty
    [ -x "$BUILDROOT/usr/bin/sed" ] || add_binary sed || return 1
    [ -x "$BUILDROOT/usr/bin/grep" ] || add_binary grep || return 1
    add_binary ip
    add_binary ping
    add_binary sysctl
}

help() {
    cat <<HELPEOF
Adds needed binaries for SKUF to initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
