#!/usr/bin/ash

run_hook() {
    termsize="$(stty size)"
    termsize="${termsize##* }"

    msg -n ":: Loading console font..."
    if [ -e /sys/firmware/efi ]; then
        if [ $termsize -gt 240 ]; then
            if [ -e /ter-k32n_consolefont.psfu ]; then
                # Supported in ash
                # shellcheck disable=SC3036
                echo -en "a\010 \010"
                setfont -C /dev/console /ter-k32n_consolefont.psfu
            elif [ -e /ter-k32n_consolefont.psf ]; then
                # Supported in ash
                # shellcheck disable=SC3036
                echo -en "a\010 \010"
                setfont -C /dev/console /ter-k32n_consolefont.psf
            else
                msg "No consolefont found despite added hook."
                return 0
            fi
        else
            if [ -e /ter-k20n_consolefont.psfu ]; then
                # Supported in ash
                # shellcheck disable=SC3036
                echo -en "a\010 \010"
                setfont -C /dev/console /ter-k20n_consolefont.psfu
            elif [ -e /ter-k20n_consolefont.psf ]; then
                # Supported in ash
                # shellcheck disable=SC3036
                echo -en "a\010 \010"
                setfont -C /dev/console /ter-k20n_consolefont.psf
            else
                msg "No consolefont found despite added hook."
                return 0
            fi
        fi
    else
        if [ -e /ter-k16n_consolefont.psfu ]; then
            # Supported in ash
            # shellcheck disable=SC3036
            echo -en "a\010 \010"
            setfont -C /dev/console /ter-k16n_consolefont.psfu
        elif [ -e /ter-k16n_consolefont.psf ]; then
            # Supported in ash
            # shellcheck disable=SC3036
            echo -en "a\010 \010"
            setfont -C /dev/console /ter-k16n_consolefont.psf
        else
            msg "No consolefont found despite added hook."
            return 0
        fi
    fi
    msg "done."
}

# vim: set ft=sh ts=4 sw=4 et:
