#!/usr/bin/ash

run_hook() {
    local mode ctrl

    if [ -e /keymap.bin ]; then
        msg -n ':: Loading keymap...'
        if [ -f /keymap.utf8 ]; then
            mode='-u'
            ctrl='G'
        else
            mode='-a'
            ctrl='@'
        fi
        kbd_mode "$mode" -C /dev/console
        printf "\033%%$ctrl" >>/dev/console
        loadkmap </keymap.bin
        ###
        stty -F /dev/console iutf8
        ###
        msg 'done.'
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
